# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161120_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=35),
        ),
    ]
